@startuml Karma Custom Bond redeem flow

Caller -> KarmaCustomBond : **deposit process flow**

note over KarmaCustomBond : \
The depositor may start redeeming payout tokens \n\
right after depositing, and receive a percent in \n\
proportion of the time elapsed depending of the \n\
bond vesting time.

@enduml