@startuml Karma Custom Bond deposit flow

group Transfer amount of principal token to the bond
  Caller -> PrincipalToken : **transfer** ( \n\
    KarmaCustomBond, \n\
    amount, { \n\
      "method": "deposit" \n\
    } \n\
  )

  PrincipalToken -> KarmaCustomBond : **tokenFallback** ( \n\
    Caller, \n\
    amount, { \n\
      "method": "deposit" \n\
    } \n\
  )
end group

note over KarmaCustomBond : \
**decayDebt()**

group Deposit the principal tokens to the Custom Treasury
  KarmaCustomBond -> PrincipalToken : **transfer** ( \n\
    KarmaCustomTreasury, \n\
    amount, { \n\
      "method": "deposit" \n\
    } \n\
  )

  PrincipalToken -> KarmaCustomTreasury : **tokenFallback** ( \n\
    KarmaCustomBond, \n\
    amount, { \n\
      "method": "deposit" \n\
    } \n\
  )
end group

group Pay the payout token back to the Custom Bond
  KarmaCustomTreasury -> PayoutToken : **transfer** ( \n\
    KarmaCustomBond, \n\
    amount, { \n\
      "method": "pay" \n\
    } \n\
  )

  PayoutToken -> KarmaCustomBond : **tokenFallback** ( \n\
    KarmaCustomTreasury, \n\
    amount, { \n\
      "method": "pay" \n\
    } \n\
  )

end group


group Transfer fee to the DAO Treasury
  KarmaCustomBond -> PrincipalToken : **transfer** ( \n\
    KarmaDAOTreasury, \n\
    amount, { \n\
      "method": "deposit" \n\
    } \n\
  )

  PrincipalToken -> KarmaDAOTreasury : **tokenFallback** ( \n\
    KarmaCustomBond, \n\
    amount, { \n\
      "method": "deposit" \n\
    } \n\
  )

end group


note over KarmaCustomBond : \
**Update totalDebt**

note over KarmaCustomBond : \
**Store Depositor Information**

note over KarmaCustomBond : \
**Increase total bonded**

note over KarmaCustomBond : \
**Increase total payout**

note over KarmaCustomBond : \
**Update subsidy counter**

note over KarmaCustomBond : \
**Adjust BCV**


@enduml