@startuml Karma Factory createBond

Caller -> KarmaFactory : **createBond** (\n\
  payoutToken,  \n\
  principalToken,  \n\
  customTreasury,  \n\
  initialOwner,  \n\
  tierCeilings, \n\
  fees \n\
)

KarmaFactory -> KarmaCustomBond : **deploy**
return bond address

KarmaFactory -> KarmaFactoryStorage : **pushBond** (details)

@enduml